const { ImapFlow } = require('imapflow');
const simpleParser = require('mailparser').simpleParser;
const prisma = require('./prisma');

const startEmailListener = async (io) => {
  const client = new ImapFlow({
    host: 'imap.gmail.com',
    port: 993,
    secure: true,
    auth: {
      user: process.env.EMAIL_USER || 'testingforcompany.0@gmail.com',
      pass: process.env.EMAIL_PASS || 'qxmj ibnc fleg gsyy'
    },
    logger: false // Set to true for deep debugging
  });
  // Handle unexpected connection errors
  client.on('error', err => {
    console.error('⚠️ IMAP Connection Error:', err.message);
  });

  client.on('close', () => {
    console.log('⚠️ IMAP Connection Closed. Attempting to reconnect in 5 seconds...');
    setTimeout(() => startEmailListener(io), 5000);
  });

  try {
    await client.connect();
    console.log('✅ Connected to Gmail IMAP successfully');

    let lock = await client.getMailboxLock('INBOX');
    try {
      // Start listening for new mails
      client.on('exists', async (data) => {
        console.log(`New email detected! Total messages in INBOX: ${data.count}`);
        
        // Fetch the latest message
        let message = await client.fetchOne(data.count, { source: true });
        if (message) {
          const parsed = await simpleParser(message.source);
          
          const fromEmail = parsed.from.value[0].address;
          const fromName = parsed.from.value[0].name || fromEmail.split('@')[0];
          const subject = parsed.subject || 'No Subject';
          const textBody = parsed.text || parsed.html || 'Empty Email';

          // Filter out automated, no-reply, and system emails
          const ignorePatterns = [
            'noreply', 'no-reply', 'donotreply', 'do-not-reply', 
            'mailer-daemon', 'bounce', 'alerts@', 'notifications@',
            '@google.com', '@facebookmail.com', '@linkedin.com'
          ];
          
          const isAutomated = ignorePatterns.some(pattern => fromEmail.toLowerCase().includes(pattern)) ||
                              parsed.headers?.get('list-unsubscribe') || 
                              parsed.headers?.get('x-autogenerated') ||
                              parsed.headers?.get('precedence') === 'bulk';

          if (isAutomated) {
            console.log(`Ignoring automated/system email from: ${fromEmail}`);
            return; // Skip processing this email
          }

          console.log(`Processing incoming email from: ${fromEmail}`);

          // 1. Find or create Customer
          let customer = await prisma.customer.findFirst({ where: { email: fromEmail } });
          
          if (!customer) {
             customer = await prisma.customer.create({
               data: {
                 name: fromName,
                 email: fromEmail,
                 phone: 'EMAIL_' + Date.now().toString(), // Dummy phone to satisfy unique constraint
               }
             });
          }

          // 2. Find open conversation or create new one
          let conversation = await prisma.conversation.findFirst({
            where: { customerId: customer.id, channel: 'EMAIL', status: 'OPEN' }
          });

          if (!conversation) {
            conversation = await prisma.conversation.create({
              data: {
                customerId: customer.id,
                channel: 'EMAIL',
                priority: 'NORMAL',
                unreadCount: 0
              }
            });
          }

          // 3. Create the message
          const savedMessage = await prisma.message.create({
            data: {
              conversationId: conversation.id,
              senderType: 'CUSTOMER',
              content: `Subject: ${subject}\n\n${textBody}`,
              status: 'DELIVERED'
            }
          });

          // 4. Update conversation unread count
          const updatedConv = await prisma.conversation.update({
            where: { id: conversation.id },
            data: { 
              unreadCount: { increment: 1 },
              updatedAt: new Date()
            },
            include: { customer: true }
          });

          // 5. Broadcast via Socket.IO
          io.emit('new_message', {
            conversationId: conversation.id,
            message: savedMessage
          });

          io.emit('newEmailMessage', {
            conversation: updatedConv,
            message: savedMessage,
            customer: customer
          });
          
          io.emit('conversationUpdated', updatedConv);
          io.emit('unreadUpdated', { conversationId: conversation.id, unreadCount: updatedConv.unreadCount });
          
          const { analyzeAndSaveConversation } = require('./ai-gemini');
          analyzeAndSaveConversation(conversation.id, io).catch(console.error);
          
          console.log('📩 Email saved to DB and broadcasted to CRM UI');
        }
      });
    } finally {
      lock.release();
    }
  } catch (err) {
    console.error('❌ Failed to connect to Gmail IMAP:', err);
  }
};

module.exports = { startEmailListener };
